version: "3"
services:
    etcd-1:
        image: quay.io/coreos/etcd:v3.5.9
        entrypoint: /usr/local/bin/etcd
        ports:
            - "2379:2379"
        command:
            - '--name=etcd-1'
            - '--initial-advertise-peer-urls=http://etcd-1:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd-1:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=etcdbogustoken1234'
        volumes:
            - ./etcd1_data:/etcd_data

    etcd-2:
        image: quay.io/coreos/etcd:v3.5.9
        entrypoint: /usr/local/bin/etcd
        command:
            - '--name=etcd-2'
            - '--initial-advertise-peer-urls=http://etcd-2:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd-2:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=etcdbogustoken1234'
        volumes:
            - ./etcd2_data:/etcd_data

    etcd-3:
        image: quay.io/coreos/etcd:v3.5.9
        entrypoint: /usr/local/bin/etcd
        command:
            - '--name=etcd-3'
            - '--initial-advertise-peer-urls=http://etcd-3:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd-3:2379'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
            - '--initial-cluster-state=new'
            - '--initial-cluster-token=etcdbogustoken1234'
        volumes:
            - ./etcd3_data:/etcd_data
