version: "3"

services:

        torch2:
                build: .
                container_name: torch2
                deploy:
                  resources:
                    reservations:
                      devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu] 
