version: "3"

services:
                        
        mysql-db:
                build: .
                container_name: mysql-db
                ports:
                        - "3306:3306"
                volumes:
                        - ./.data:/var/lib/mysql
        