version: "3"

services:

        torch1:
                build: .
                container_name: torch1
                deploy:
                  resources:
                    reservations:
                      devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu] 