turnServerAddr:
  - addr: turn:192.168.122.106:3478
    id: hello
    pw: example

rooms:
  - key: abcd
    members:
      - hello
      - world

url: "192.168.122.106"

signalPort: 8002

rtpReceivePort: 8004

peerSignalAttemptSync: 5

peerSignalAddr : /signal/peer/

rtcpPLIInterval: 3

udpMuxPort: 8006

udpEphemeralPortMin: 31000
udpEphemeralPortMax: 31100
